name: Manual CI Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: string 
        default: dev
        required: false
      version:
        description: "Version"
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Printing env values
        run: |
          echo Environment: ${{ inputs.environment }}
          echo Version: ${{ inputs.version }}

