name: CI Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Printing values
        run: echo Deploying to ${{ inputs.environment }}

